version: "3"
services:
  vision:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: "vision"
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --reload"
    restart: always
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
    depends_on:
      - dev_db
      - test_db

  dev_db:
    image: postgres:14
    container_name: "dev_db"
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  test_db:
    image: postgres:14
    container_name: "test_db"
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5433:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres:
    external: false
