"""add ProductValue relationship to attributes

Revision ID: 68ca02cca2d1
Revises: 7e9eeb679f0b
Create Date: 2025-12-26 18:03:33.527848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ca02cca2d1'
down_revision = '7e9eeb679f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'PRODUCT_MODEL', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_entity_attr_scope_locale', 'product_values', ['entity_type', 'entity_id', 'attribute_id', 'scope', 'locale'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_entity_attr_scope_locale', table_name='product_values')
    op.drop_table('product_values')
    # ### end Alembic commands ###