"""add labels to family table

Revision ID: 9333f67d9d37
Revises: 68ca02cca2d1
Create Date: 2025-12-26 18:11:48.025931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9333f67d9d37'
down_revision = '68ca02cca2d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('labels', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'labels')
    # ### end Alembic commands ###