"""Add attributes and update foreign keys

Revision ID: 9cac49144ad4
Revises: ee1c19f9e51d
Create Date: 2025-10-23 22:25:25.461487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cac49144ad4'
down_revision = 'ee1c19f9e51d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###