"""add timestamp to family model

Revision ID: d7c796b8849f
Revises: 5a4a155e432e
Create Date: 2026-01-30 23:15:13.567001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c796b8849f'
down_revision = '5a4a155e432e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('families', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'updated_at')
    op.drop_column('families', 'created_at')
    # ### end Alembic commands ###