"""Add attributes tabel

Revision ID: ee1c19f9e51d
Revises: da9c221966f6
Create Date: 2025-10-23 22:13:00.932300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1c19f9e51d'
down_revision = 'da9c221966f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('backend_type', sa.String(), nullable=False),
    sa.Column('is_localizable', sa.Boolean(), nullable=True),
    sa.Column('is_scopable', sa.Boolean(), nullable=True),
    sa.Column('group_code', sa.String(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('attribute_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('attribute_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute_options')
    op.drop_table('attributes')
    # ### end Alembic commands ###